### ISSUE TITLE
\ acting as escape character in strings

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#23]
In a string, `\` can escape certain characters, e.g. ``` `\\` ``` pushes `\`; ``` `\`` ``` pushes ``` \` ```. Not sure if it's intentional, but it isn't documented anywhere.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%60%5C%5C%60%2C%0A%60%5C%60%60%2C%0A%60%5C%5C%5C%60%60%2C&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
Except for

```
`\``
```

The backslash is indeed supposed to be able to escape characters in strings much like in most practical languages. Also, backslahes allow you to include characters that would otherwise be used for dictionary compression.

Not sure what's happening with escaping the backtick though. I'll have to look into that when I'm next at my computer (which won't be for another 10 or so hours)
