### ISSUE TITLE
∆T does not work

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#49]
The `∆T` command, or transpose, does not return the expected output.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%E2%9F%A81%7C2%7C3%E2%9F%A9%7C%E2%9F%A84%7C5%7C6%E2%9F%A9%7C%E2%9F%A87%7C8%7C9%E2%9F%A9%E2%9F%A9%E2%88%86T&inputs=&header=&footer=)

The above example is taken directly from the documentation for this command.

**Comment by Lyxal** [comment]
That's because it's actually `ÞT` that transposes lists. 

`∆` is for mathematical digraphs (all functions with that symbol are math related) while `Þ` is for list digraphs (all functions with that symbol are list related) 


[Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%E2%9F%A81%7C2%7C3%E2%9F%A9%7C%E2%9F%A84%7C5%7C6%E2%9F%A9%7C%E2%9F%A87%7C8%7C9%E2%9F%A9%E2%9F%A9%C3%9ET&inputs=&header=&footer=)
